development:
  adapter: postgresql
  encoding: utf8
  database: db/development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: db/test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: db/production
  pool: 5
  username: 
  password:
